# Generated by Django 4.2.11 on 2024-04-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('code', models.CharField(help_text='local_folder_path', max_length=300, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='channel_YYYYMMDDThhmmss format', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyframe',
            fields=[
                ('path', models.CharField(help_text='local_path', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='channel_YYYYMMDDThhmmss_s(n_seconds)_f(n-frame) format', max_length=200, null=True)),
                ('timecode', models.CharField(help_text='hh:mm:ss.f format', max_length=200, null=True)),
                ('category', models.ManyToManyField(blank=True, to='annotationV1.category')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotationV1.video')),
            ],
        ),
    ]
