# Generated by Django 4.2.11 on 2024-04-24 08:34

import annotationV1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationV1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframe',
            name='annotated',
            field=models.JSONField(default=annotationV1.models.default_annotated, null=True),
        ),
    ]
